// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplatedish = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://savla.dev/swapi",
            "email": "info@savla.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dish/test": {
            "head": {
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    }
}`

// SwaggerInfodish holds exported Swagger Info so clients can modify it
var SwaggerInfodish = &swag.Spec{
	Version:          "5.1",
	Host:             "",
	BasePath:         "/dish",
	Schemes:          []string{},
	Title:            "swis-api v5",
	Description:      "dish swapi module",
	InfoInstanceName: "dish",
	SwaggerTemplate:  docTemplatedish,
}

func init() {
	swag.Register(SwaggerInfodish.InstanceName(), SwaggerInfodish)
}
